config/routes.rb
Rails.application.routes.draw do
  resources :visitors, only: [:new, :create]
  root to: 'visitors#new'
  get '/about', to: 'visitors#about'
  get '/contact', to: 'visitors#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/visitor.rb
class Visitor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(params.require(:visitor).permit(:email))
    if @visitor.save
      redirect_to root_path, notice: "Signed up #{@visitor.email}."
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <%= link_to "Home", root_path %>
  <%= render 'layouts/navigation_links' %>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<%= link_to "About", about_path %>
<%= link_to "Contact", contact_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Efraim" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Efraim" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400" rel="stylesheet">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/visitors/_media.html.erb
<ul id="social">
  <a class="social" target="_blank" href="https://www.facebook.com/EfraimLeoOfficial/">
    <i class="fa fa-facebook" aria-hidden="true"></i>
  </a>
  <a class="social" target="_blank" href="https://twitter.com/efraimleomusic">
    <i class="fa fa-twitter" aria-hidden="true"></i>
  </a>
  <a class="social" target="_blank" href="https://www.instagram.com/grndvw/">
    <i class="fa fa-instagram" aria-hidden="true"></i>
  </a>
  <a class="social" target="_blank" href="https://www.youtube.com/user/efraimleo">
    <i class="fa fa-youtube" aria-hidden="true"></i>
  </a>
  <a class="social" target="_blank" href="https://open.spotify.com/artist/3SwHW7YiRPiqokx3zCpyit?si=8KSHv2SmRMqIthITatKGCw">
    <i class="fa fa-spotify" aria-hidden="true"></i>
  </a>
</ul>

app/views/visitors/_social.html.erb
<div id="media">
  <div class="col-md-12 col-sm-12 col-xs-11" id="spotify">
    <h1>"You Got Me Wrong"</h1>
    <h1>Available Now</h1>
    <ul>
      <a class="social" target="_blank" href="https://open.spotify.com/artist/3SwHW7YiRPiqokx3zCpyit?si=8KSHv2SmRMqIthITatKGCw">
        <i class="fa fa-spotify" aria-hidden="true"></i>
      </a>
      <a class="social" target="_blank" href="#">
        <i class="fa fa-amazon" aria-hidden="true"></i>
      </a>
      <a class="social" target="_blank" href="#">
        <i class="fa fa-apple" aria-hidden="true"></i>
      </a>
      <a class="social" target="_blank" href="https://www.youtube.com/user/efraimleo">
        <i class="fa fa-youtube" aria-hidden="true"></i>
      </a>
      <a class="social" target="_blank" href="https://soundcloud.com/efraim-leo">
        <i class="fa fa-soundcloud" aria-hidden="true"></i>
      </a>
    </ul>
  </div>
</div>

app/views/visitors/_tour.html.erb
<h1>Tour Dates</h1>
<table class='table borderless'>
  <tbody>
    <tr>
      <td class="col-1">Nov 11</td>
      <td class="col-1">Sun</td>
      <td class="col-2">Granada Theater</td>
      <td>Dallas, TX</td>
      <td class="col-3"><button>Tickets</button><button>RSVP</button></td>
    </tr>
    <tr>
      <td class="col-1">Dec 31</td>
      <td class="col-1">Sat</td>
      <td class="col-2">Granada Theater</td>
      <td>Dallas, TX</td>
      <td class="col-3"><button>Tickets</button><button>RSVP</button></td>
    </tr>
    <tr>
      <td class="col-1">Jan 6</td>
      <td class="col-1">Sat</td>
      <td class="col-2">Music Fest'l</td>
      <td>Steamboat Springs, CO</td>
      <td class="col-3"><button>Tickets</button><button>RSVP</button></td>
    </tr>
    <tr>
      <td class="col-1">Jan 7</td>
      <td class="col-1">Sun</td>
      <td class="col-2">Music Fest'l</td>
      <td>Steamboat Springs, CO</td>
      <td class="col-3"><button>Tickets</button><button>RSVP</button></td>
    </tr>
    <tr>
      <td class="col-1">Jan 8</td>
      <td class="col-1">Mon</td>
      <td class="col-2">Music Fest'l</td>
      <td>Steamboat Springs, CO</td>
      <td class="col-3"><button>Tickets</button><button>RSVP</button></td>
    </tr>
    <tr>
      <td class="col-1">Jan 21</td>
      <td class="col-1">Sun</td>
      <td class="col-2">Howlin Wolf</td>
      <td>New Orleans, LA</td>
      <td class="col-3"><button>Tickets</button><button>RSVP</button></td>
    </tr>
    <tr>
      <td class="col-1">Jan 22</td>
      <td class="col-1">Mon</td>
      <td class="col-2">Outlaw Country Cruise</td>
      <td>New Orleans, LA</td>
      <td class="col-3"><button>Tickets</button><button>RSVP</button></td>
    </tr>
    <tr>
      <td class="col-1">Jan 23</td>
      <td class="col-1">Tue</td>
      <td class="col-2">Outlaw Country Cruise</td>
      <td>New Orleans, LA</td>
      <td class="col-3"><button>Tickets</button><button>RSVP</button></td>
    </tr>
    <tr>
      <td class="col-1">Jan 24</td>
      <td class="col-1">Wed</td>
      <td class="col-2">Outlaw Country Cruise</td>
      <td>New Orleans, LA</td>
      <td class="col-3"><button>Tickets</button><button>RSVP</button></td>
    </tr>
    <tr>
      <td class="col-1">Jan 25</td>
      <td class="col-1">Thur</td>
      <td class="col-2">Outlaw Country Cruise</td>
      <td>New Orleans, LA</td>
      <td class="col-3"><button>Tickets</button><button>RSVP</button></td>
    </tr>
    <tr>
      <td class="col-1">Jan 26</td>
      <td class="col-1">Fri</td>
      <td class="col-2">Outlaw Country Cruise</td>
      <td>New Orleans, LA</td>
      <td class="col-3"><button>Tickets</button><button>RSVP</button></td>
    </tr>
  </tbody>
</table>

app/views/visitors/about.html.erb
<div id="about">
  <h1>About Efraim Leo</h1>
  <p>The world we are living in today is quite complex, "professes 20 year old,
    Efraim Leo. "I want to move people; make them feel emotions
    and to help them not feel like they are stuck," he proclaims</p>

  <p>With a penchant for introspective lyrical narrative for
    icy pop moldies that burn with a steady emotive urgency,
    Efraim Leo arrives with his new single, "You Got Me Wrong," via 300 Entertainment.
    A dazzling pop gem reminiscent of acts like Sawn Mendes or James Arthur,
    it's hard to believe that Efraim wasn't always so upbeat when it came to songwriting.
  </p>

  <p>
    First picking up a guitar when he was 13 years old, Efraim Leo arrived at songwriting status when he realised the poems he had been composing could double as lyrics.
    "I've always written stuff - whether it be lyrics or poems, but when I picked up the guitar I realized I could write songs," he explains.
  </p>

  <p>
    Always feeling like an outsider and heavily influenced by the rambling stylings of artists like Bob Dylan and the genre bending sound of Queen, Efraim was penning emotionally charged music about what he
    was encountering everyday as a teenager. "When I went to elementary school, I was bulled by a really mean guy and everyone in our class was super afraid of him,
    and no one could do anything about. I wrote about what effect this guy had on my life and how I felt about the situation."
  </p>

  <p>
    While his songwriting style has changed and he began to write lyrics that resembled
    hip hop prose, the pain didn't stop when he graduated to high school. Dealing with internal struggles
    within his family, with a sibling who suffered from depression, Efraim didn't have the energy for school work,
    but when he sat with his guitar, it was a different story.
  </p>

  <p>
    "I had a safe space - when I went to high school I struggled with depression, and I didn't feel like
    I was enough and it felt like everything I did was a waste of time. But when I sat with my guitar
    and just sang with those feelings in my mind or the words I was thinking about I felt like everything would be ok. I felt safe, like I was on top of the world."
  </p>

  <p>
    The Swedish singer songwriter hold an affinity for movies especially those by Christopher Noaln and his all time favourite, Pulp Fiction - he never finished high school, and poured his heart and soul into music instead.
  </p>

  <p>
    Efraim lent his vocals to fellow Swedish artist, MARC's track, "Show You The Light" which has since garnered over 13 million Spotify streams. A chance session with some visiting producers lead to his first solo hit, "You Got Me Wrong."
  </p>

  <p>
    "I think it was almost a year ago, and Juliette Claire and Clifford Gallio TK - came from Amsterdam and we weren't meant to do a session - they do mostly dance music. But they
    had a day off and so we just started writing, and we were focusing on my sound at the time. They had this idea that we could make a duet, and we just started writing and everything went so fast.
    I think we wrote the song and had a really good demo in less than 5 hours."
  </p>

  <p>
    It was "You Got Me Wrong," that sealed the deal with 300 Entertainment - "a few days after writing the song, we shed them the track and they went crazy. It was kind of like, that song is the song that made me end up here."
  </p>

  <p>
    With an infectious guitar riff and a slow burning bass line, "You Got Me Wrong" is an exuberant first taste of Efraim Leo that is just the first glimpse of what's to come.
  </p>

  <p>
    "I've always said that if I was ever able to ever have my music reach people, if I move people and get my lyrics out and people can relate to them,
    then that's where I've succeeded."
  </p>
</div>

app/views/visitors/contact.html.erb
<div id="contact">
  <h1>Contact Efraim Leo</h1>
  <h5>Management: <br>
  Elaine Music Management</h5>
</div>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-md-3">
            <p class="lead">Shop Name</p>
            <div class="list-group">
                <a href="#" class="list-group-item">Category 1</a>
                <a href="#" class="list-group-item">Category 2</a>
                <a href="#" class="list-group-item">Category 3</a>
            </div>
        </div>

        <div class="col-md-9">

            <div class="row carousel-holder">

                <div class="col-md-12">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="slide-image" src="http://placehold.it/800x300" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="http://placehold.it/800x300" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image" src="http://placehold.it/800x300" alt="">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>

            </div>

            <div class="row">

                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="http://placehold.it/320x150" alt="">
                        <div class="caption">
                            <h4 class="pull-right">$24.99</h4>
                            <h4><a href="#">First Product</a>
                            </h4>
                            <p>See more snippets like this online store item at <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
                        </div>
                        <div class="ratings">
                            <p class="pull-right">15 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="http://placehold.it/320x150" alt="">
                        <div class="caption">
                            <h4 class="pull-right">$64.99</h4>
                            <h4><a href="#">Second Product</a>
                            </h4>
                            <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                        <div class="ratings">
                            <p class="pull-right">12 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="http://placehold.it/320x150" alt="">
                        <div class="caption">
                            <h4 class="pull-right">$74.99</h4>
                            <h4><a href="#">Third Product</a>
                            </h4>
                            <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                        <div class="ratings">
                            <p class="pull-right">31 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="http://placehold.it/320x150" alt="">
                        <div class="caption">
                            <h4 class="pull-right">$84.99</h4>
                            <h4><a href="#">Fourth Product</a>
                            </h4>
                            <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                        <div class="ratings">
                            <p class="pull-right">6 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="http://placehold.it/320x150" alt="">
                        <div class="caption">
                            <h4 class="pull-right">$94.99</h4>
                            <h4><a href="#">Fifth Product</a>
                            </h4>
                            <p>This is a short description. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                        </div>
                        <div class="ratings">
                            <p class="pull-right">18 reviews</p>
                            <p>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star"></span>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-sm-4 col-lg-4 col-md-4">
                    <h4><a href="#">Like this template?</a>
                    </h4>
                    <p>If you like this template, then check out <a target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">this tutorial</a> on how to build a working review system for your online store!</p>
                    <a class="btn btn-primary" target="_blank" href="http://maxoffsky.com/code-blog/laravel-shop-tutorial-1-building-a-review-system/">View Tutorial</a>
                </div>

            </div>

        </div>

    </div>

</div>
<!-- /.container -->

<div class="container">

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
    </footer>

</div>
<!-- /.container -->

app/views/visitors/new.html.erb
<section id="header-bg">
  <h1>Efraim Leo</h1>
  <%= render "media" %>
  <iframe src="https://open.spotify.com/embed?uri=spotify:track:00zDYS7mdF0y7emh6Deqim" width="300" height="80" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
  <%= render "social" %>
</section>
<section id="youtube-section">
  <div class="col-md-12">
    <iframe id="youtube" src="https://www.youtube.com/embed/nzKqmPTEdUg" frameborder="0" encrypted-media="allowfullscreen">
    </iframe>
  </div>
</section>
<section>
  <div class="col-md-offset-1 col-md-10">
    <%= render "tour" %>
  </div>
</section>